---
abstract: 'CSS Style switcher plugin'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-StyleSwitcher
provides:
  App::ZofCMS::Plugin::StyleSwitcher:
    file: lib/App/ZofCMS/Plugin/StyleSwitcher.pm
    version: 0.0103
requires:
  App::ZofCMS: 0.0106
  App::ZofCMS::Plugin::Base: 0.0102
  DBI: 1.602
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
