---
name: App-ZofCMS-Plugin-StyleSwitcher
version: 0.0102
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: CSS Style switcher plugin
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS: 0.0106
  App::ZofCMS::Plugin::Base: 0.0102
  DBI: 1.602
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::StyleSwitcher:
    file: lib/App/ZofCMS/Plugin/StyleSwitcher.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
